"""
Crypto Trading Agents - Configuration
Hyperliquid Testnet + Telegram via OpenClaw
"""

# === HYPERLIQUID TESTNET ===
HYPERLIQUID_TESTNET = True
HYPERLIQUID_API_KEY = "DEIN_API_KEY_HIER"
HYPERLIQUID_API_SECRET = "DEIN_API_SECRET_HIER"
HYPERLIQUID_BASE_URL = "https://api.hyperliquid-testnet.xyz"

# === TRADING PAIRS ===
PRIMARY_PAIRS = ["BTC", "ETH"]
SECONDARY_PAIRS = ["SOL", "DOGE", "XRP"]

# === SCAN SETTINGS ===
PRIMARY_SCAN_INTERVAL = 15
SECONDARY_SCAN_INTERVAL = 60
TIMEFRAMES = ["15m", "1h", "4h", "1d"]
WEEKLY_TIMEFRAME = "1w"

# === INDICATORS ===
RSI_PERIOD = 14
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
BB_PERIOD = 20
BB_STD = 2
EMA_PERIODS = [21, 50, 100, 200]
VOLUME_SPIKE_MULTIPLIER = 2.0
OI_CHANGE_THRESHOLD = 5.0
FUNDING_RATE_HIGH = 0.03
FUNDING_RATE_LOW = -0.03

# === CONFLUENCE ===
HIGH_CONFLUENCE_MIN_INDICATORS = 3
HIGH_CONFLUENCE_MIN_TIMEFRAMES = 2
MEDIUM_CONFLUENCE_MIN = 2

# === RISK MANAGEMENT ===
MAX_RISK_PER_TRADE = 0.02
MAX_OPEN_POSITIONS = 3
MAX_DIRECTIONAL_EXPOSURE = 0.05
MIN_RR_RATIO = 2.0
MAX_DAILY_LOSS = 0.05
MAX_WEEKLY_LOSS = 0.10
MAX_MONTHLY_LOSS = 0.20
CONSECUTIVE_LOSS_LIMIT = 3
REDUCED_RISK = 0.01
TRAILING_BREAKEVEN = 0.02
TRAILING_50 = 0.05
TRAILING_70 = 0.10

# === BACKTEST ===
BACKTEST_DAYS = 180
BACKTEST_MIN_TRADES = 10
BACKTEST_CACHE_DAYS = 7
SLIPPAGE = 0.001
TRADING_FEE = 0.0005
BACKTEST_TIMEOUT_HOURS = 48

# === ALERTS ===
MAX_ALERTS_PER_HOUR = 5
ALERT_COOLDOWN_MINUTES = 60
QUIET_HOURS_START = 23
QUIET_HOURS_END = 6
TIMEZONE = "Europe/Berlin"

# === SCHEDULE ===
DAILY_RESEARCH_HOUR = 7
MORNING_BRIEFING_HOUR = 8
PORTFOLIO_CHECK_MORNING = 9
PORTFOLIO_CHECK_EVENING = 21
EOD_SUMMARY_HOUR = 22
WEEKLY_DEEP_DIVE_DAY = 0
WEEKLY_REVIEW_DAY = 6

# === TELEGRAM ===
TELEGRAM_BOT_TOKEN = "8633981943:AAHzKFHwR3WF-orxKFUalrw4IL92bXGT1mE"
TELEGRAM_CHAT_ID = ""

# === STORAGE ===
DATA_DIR = "/data/crypto-agents"
LOG_DIR = "/data/crypto-agents/logs"
SCAN_LOG_DIR = "/data/crypto-agents/scans"
BACKTEST_CACHE_DIR = "/data/crypto-agents/backtest_cache"
PORTFOLIO_FILE = "/data/crypto-agents/portfolio.json"
ALERTS_LOG = "/data/crypto-agents/alerts_log.json"

INITIAL_PORTFOLIO_VALUE = 10000
